---
title: "Title of Your Report"
author: "Guemin Kim, Woolim Kim"
date: "Oct 19, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
data <- read_csv("gss.csv")
data
life_satisfaction_data <- data %>% 
  select(caseid, age, sex, feelings_life, self_rated_health, self_rated_mental_health, 
         income_family, average_hours_worked) %>% 
  mutate(self_rated_health = case_when(self_rated_health == "Excellent" ~ 5, 
                                       self_rated_health == "Very good" ~ 4, 
                                       self_rated_health == "Good" ~ 3, 
                                       self_rated_health == "Fair" ~ 2, 
                                       self_rated_health == "Poor" ~1, 
                                       self_rated_health == "Don't know" ~ 0)) %>%
  mutate(self_rated_mental_health = case_when(self_rated_mental_health == "Excellent" ~ 5, 
                                              self_rated_mental_health == "Very good" ~ 4, 
                                              self_rated_mental_health == "Good" ~ 3, 
                                              self_rated_mental_health == "Fair" ~ 2, 
                                              self_rated_mental_health == "Poor" ~1, 
                                              self_rated_mental_health == "Don't know" ~ 0)) %>%
  filter(self_rated_health != 0, self_rated_mental_health != 0, 
         average_hours_worked != "Don't know")
life_satisfaction_data

# General Linear Regression Model
satisfaction_lm <- lm(feelings_life ~ as.factor(self_rated_health)+ as.factor(self_rated_mental_health) + income_family + average_hours_worked, data = life_satisfaction_data)
summary(satisfaction_lm)

# Linear Regression Model (Predictor: health rating)
lm1 <- lm(feelings_life ~ as.factor(self_rated_health), data = life_satisfaction_data)
summary(lm1)

# Linear Regression Model (Predictor: income of the family)
lm2 <- lm(feelings_life ~ income_family, data = life_satisfaction_data)
summary(lm2)

# Linear Regression Model (Predictor: )
lm3 <- lm(feelings_life ~ average_hours_worked, data = life_satisfaction_data)
summary(lm3)

immigrant_data <- data %>% select(caseid, age, sex, feelings_life, 
                                  age_immigration, landed_immigrant, citizenship_status) %>%
  filter(landed_immigrant != "Don't know", citizenship_status != "Don't know")
table(immigrant_data$citizenship_status)

# Logit Regression Model
# lm4 <- lm(feelings_life ~ as.factor(landed_immigrant), data = immigrant_data, family = "binomial")
# summary(lm4)
```

## Title of your Report

# Name(s) of Author(s) 
# Date

## Abstract

Here is where you give a brief (one paragraph overview of your entire paper). This should include some background/introduction, some methodology, results and conclusions.

## Introduction

Here is where you should give insight into the setting and introduce the goal of the analysis. Here you can introduce ideas and basic concepts regarding the study setting and the potential model. Again, this is the introduction, so you should be explaining the importance of the work that is ahead and hopefully build some suspense for the reader. You can also highlight what will be included in the subsequent sections.

## Data

Introduce the data, explain why it was selected. Make sure to comment on important features and highlight any potential drawbacks to the data.

## Model

Introduce the selected model here. It is expected that you will use some mathematical notation here. If you do please ensure that all notation is explained. You may also want to discuss any special (hypothetical) cases of your model here, as well as any caveats.  

## Results

Here you will include all results. This includes descriptive statistics, graphs, figures, tables, and model results. Please ensure that everything is well formatted and in a report style. You must also provide an explanation of the results in this section. You can overflow to an Appendix if needed. 

Please ensure that everything is well labelled. So if you have multiple histograms and plots, calling them Figure 1, 2, 3, etc. and referencing them as Figure 1, Figure 2, etc. in your report will be expected. The reader should not get lost in a sea of information. Make sure to have the results be clean, well formatted and digestible.

## Discussion

Here you will discuss conclusions drawn from the results and comment on how it relates to the original goal of the study (which was specified in the Introduction).

# Weaknesses

Here we discuss weaknesses of the study, data, analysis, etc. You can also discuss areas for improvement.

# Next Steps

Here you discuss subsequent work to be done after this report. This can include next steps in terms of statistical analysis (perhaps there is a more efficient algorithm available, or perhaps there is a caveat in the data that would allow for some new technique). Future steps should also be specified in terms of the study setting (eg. including a follow-up survey on something, or a subsequent study that would complement the conclusions of your report).


## References



